squareFun – Minimum FORD example
squareFun Function
6 statements
Source File
public function squareFun(x) result(y)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
Return Value real(kind=wp), dimension(size(x))
Called By
Source Code
squareFun
Source Code
  function squareFun(x) result(y)
    real(wp), intent(in), dimension(:)  :: x
    real(wp),             dimension(size(x))  :: y
    y = x * x
    return
  end function squareFun
All Procedures
executeFun executeFun fun_interf funWrapper funWrapper square_local squareFun squareWrapperExternal squareWrapperExternal squareWrapperInternal squareWrapperInternal
Call graph
main calls squarefun, squarewrapperinternal, square_local, squarewrapperexternal
squarewrapperinternal calls squarefun
square_local calls squarefun
squarewrapperexternal calls squarefun
main_ex calls square_local